ARK_API_KEY : "d0666bb8-8a41-42f4-bd06-94ca6ba08457"
ARK_MODEL : "doubao-seed-1-6-250615"
EMBEDDER_MODEL : "doubao-embedding-text-240715" # embedder model

# Milvus configuration
MILVUS_ADDRESS: 'localhost:19530'
MILVUS_COLLECTION: 'eino_test'