services:
  # AI文档助手主应用 - 复用现有环境
  ai-doc-assistant:
    build:
      context: .
      dockerfile: docker/Dockerfile.simple
    container_name: ai-doc-assistant-app
    ports:
      - '8080:8080'
    environment:
      - AI_DOC_SERVER_PORT=8080
      - AI_DOC_SERVER_MODE=debug
      # 复用现有服务的主机端口连接
      - AI_DOC_DATABASE_MILVUS_HOST=host.docker.internal
      - AI_DOC_DATABASE_MILVUS_PORT=19530
      - AI_DOC_DATABASE_MILVUS_DATABASE=ai_assistant
      - AI_DOC_DATABASE_MYSQL_HOST=host.docker.internal
      - AI_DOC_DATABASE_MYSQL_PORT=3309
      - AI_DOC_DATABASE_MYSQL_USERNAME=root
      - AI_DOC_DATABASE_MYSQL_PASSWORD=123456
      - AI_DOC_DATABASE_MYSQL_DATABASE=ai_assistant
      - AI_DOC_DATABASE_REDIS_HOST=host.docker.internal
      - AI_DOC_DATABASE_REDIS_PORT=6379
      # API密钥
      - AI_DOC_AI_API_KEY=d0666bb8-8a41-42f4-bd06-94ca6ba08457
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 20s
      retries: 3

  # Web界面服务 (可选)
  web:
    image: nginx:alpine
    container_name: ai-assistant-web
    ports:
      - '8081:80'
    volumes:
      - ./web/dist:/usr/share/nginx/html:ro
      - ./nginx/simple.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ai-doc-assistant
    restart: unless-stopped

# 不需要额外的volumes和networks - 复用现有环境