# AI文档助手配置文件

# 服务器配置
server:
  port: 8080
  mode: "debug"  # debug, release, test

# 数据库配置
database:
  # MySQL配置 (适配现有环境)
  mysql:
    host: "mysql8"  # MySQL容器名
    port: 3306      # 容器内端口
    username: "root"
    password: "123456"
    database: "ai_assistant"
    charset: "utf8mb4"
    max_idle_conns: 10
    max_open_conns: 100

  # Milvus向量数据库配置 (复用现有服务)
  milvus:
    host: "milvus-standalone"  # 使用现有容器名
    port: 19530
    database: "ai_assistant"
    username: ""
    password: ""

  # Redis配置 (适配现有环境)
  redis:
    host: "redis6"  # Redis容器名
    port: 6379
    password: ""
    db: 0
    pool_size: 10

# AI服务配置
ai:
  provider: "volcengine"  # volcengine, openai
  api_key: "d0666bb8-8a41-42f4-bd06-94ca6ba08457"  # 请替换为您的API密钥
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  models:
    embedding: "doubao-embedding-text-240715"  # 向量化模型
    chat: "doubao-seed-1-6-250615"           # 聊天模型

# 存储配置
storage:
  type: "local"  # local, oss, s3
  local:
    upload_path: "./uploads"
  max_file_size: "100MB"
  allowed_extensions: [".pdf", ".docx", ".txt", ".md", ".xlsx", ".pptx"]

# 日志配置
log:
  level: "info"  # debug, info, warn, error
  file: "./logs/app.log"
  max_size: 100      # MB
  max_backups: 5     # 备份文件数量

# 飞书配置（可选）
feishu:
  app_id: "your-feishu-app-id"
  app_secret: "your-feishu-app-secret"
  base_url: "https://open.feishu.cn"