# AI文档助手演示配置文件

# 服务器配置
server:
  port: 8080
  mode: "debug"

# 数据库配置（演示模式使用现有Milvus）
database:
  milvus:
    host: "localhost"
    port: 19530
    database: "ai_assistant_demo"
    username: ""
    password: ""

# AI服务配置
ai:
  provider: "volcengine"
  api_key: "${AI_DOC_AI_API_KEY}"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  models:
    embedding: "doubao-embedding"
    chat: "doubao-seed"

# 存储配置
storage:
  type: "local"
  local:
    upload_path: "./uploads"
  max_file_size: "100MB"
  allowed_extensions: [".pdf", ".docx", ".txt", ".md", ".xlsx", ".pptx"]

# 日志配置
log:
  level: "info"
  file: "./logs/app.log"
  max_size: 100
  max_backups: 5
